extends Node

signal complete(option)


func _on_new_game_button_pressed() -> void:
	emit_signal('complete', 'new game')
	return


func _on_quit_button_pressed() -> void:
	emit_signal('complete', 'quit')
	return


func _on_Quit_Button_mouse_entered() -> void:
	get_node("Menu-Select").play(0.0)
	return


func _on_Credits_Button_mouse_entered() -> void:
	get_node("Menu-Select").play(0.0)
	return


func _on_Settings_Button_mouse_entered() -> void:
	get_node("Menu-Select").play(0.0)
	return


func _on_New_Game_Button_mouse_entered() -> void:
	get_node("Menu-Select").play(0.0)
	return
